[target.aarch64-unknown-linux-gnu]
#linker = "/usr/bin/clang-14"
linker = "/usr/bin/aarch64-linux-gnu-gcc-12"
#rustflags = [ "-C", "linker=clang-14",  # change the version as needed ]
#rustflags = [ "-C", "link-arg=-fuse-ld=lld" ]

#linker = "/usr/bin/clang-cl-14"

[target.aarch64-apple-darwin]
#rustflags = [ "-C", "linker=clang-14",  # change the version as needed ]

[target.x86_64-unknown-linux-gnu]
rustflags = [ "-C", "link-arg=-fuse-ld=lld" ]

[target.x86_64-pc-windows-gnu]
linker = "/usr/bin/x86_64-w64-mingw32-gcc"

[target.x86_64-pc-windows-msvc]
rustflags = [ "-C", "link-arg=-fuse-ld=lld" ]

[build]
target = ['x86_64-unknown-linux-gnu']
#target = ['aarch64-unknown-linux-gnu','x86_64-unknown-linux-gnu',"x86_64-pc-windows-gnu"]

[alias]
test-arm-linux = "test --target=aarch64-unknown-linux-gnu"
test-pc-linux = "test --target=x86_64-unknown-linux-gnu"
test-win = "test --target=x86_64-w64-mingw32-gcc"
